#!/bin/sh

cd "$(dirname "$0")"

#=============
#Copy Files
#=============
rm -rf ./data
cp -rf  ./Web ./data
rm ./data/img/screenshot.png
rm ./data/img/charger.png

purgecss --css data/bootstrap.css --content data/*.html --whitelist bg-success,bg-danger,bg-warning --output data/css/bootstrap.css
purgecss --css data/bootstrap.slate.css --content data/*.html --whitelist bg-success,bg-danger,bg-warning  --output data/css/bootstrap.slate.css
purgecss --css data/roundslider.css --content data/*.html --whitelist --output data/css/roundslider.css
purgecss --css data/rangeslider.css --content data/*.html --whitelist --output data/css/rangeslider.css

#==============
#Download Tool
#==============
mkdir -p tools
if [ ! -f tools/mkspiffs ]; then
    curl -L -o tools/mkspiffs-0.2.3-arduino-esp8266-osx.tar.gz -k -C - https://github.com/igrr/mkspiffs/releases/download/0.2.3/mkspiffs-0.2.3-arduino-esp8266-osx.tar.gz
    cd tools
    gunzip -c mkspiffs-0.2.3-arduino-esp8266-osx.tar.gz | tar xopf -
    mv mkspiffs-0.2.3-arduino-esp8266-osx/mkspiffs ./
    rm -rf mkspiffs-0.2.3-arduino-esp8266-osx
    rm -rf mkspiffs-0.2.3-arduino-esp8266-osx.tar.gz
    cd ../
fi

for f in $(find data -type f -name '*.*'); do
    gzip "$f"
    mv "$f.gz" "$f"
done

#==============
#Compress Files
#==============
./tools/mkspiffs -c ./data/ -b 8192 -p 256 -s 440000 flash-spiffs.bin