#!/bin/sh

cd "$(dirname "$0")"

echo " > Flash Filesystem (SPIFFS)? (y/n)"
read yn
if [ $yn = y ]; then
    if [[ ! $(type -p pip) ]]; then
        cd ~/Downloads
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        python get-pip.py --user --no-warn-script-location
    fi

    pip install pyserial --user
    pip install esptool --user

    shopt -s nocasematch
    
    cu=$(ls /dev/cu.* && ls /dev/ttyUSB*)
    for serial in $cu; do
        if [[ $serial == *usb* ]] || [[ $serial == *ch34* ]] || [[ $serial == *pl23* ]] ; then
            esptool.py --port $serial --baud 115200 write_flash 0x100000 flash-spiffs.bin
            break
        fi
    done
fi